services:
  otel-collector:
    container_name: otel
    platform: linux/amd64
    image: otel/opentelemetry-collector:latest
    ports:
      - "4317:4317" ## grpc ingest
    volumes:
      - ./observability/otel-collector.yaml:/config/otel-collector.yaml
    command:
      - --config=/config/otel-collector.yaml
  jaeger-init:
    image: busybox
    user: "0"
    volumes:
      - jaeger-data:/badger
    command: sh -c "mkdir -p /badger/key /badger/data && chown -R 10001:10001 /badger"

  jaeger:
    image: jaegertracing/all-in-one:latest
    depends_on:
      jaeger-init:
        condition: service_completed_successfully
    user: "10001"
    volumes:
      - jaeger-data:/badger
    environment:
      - SPAN_STORAGE_TYPE=badger
    command:
      - --badger.ephemeral=false
      - --badger.directory-value=/badger/data
      - --badger.directory-key=/badger/key
    ports:
      - "16686:16686" ## Jaeger UI

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"

volumes:
  grafana-data:
  jaeger-data:
